"""CR091 package-driven strategy runner offline contracts."""

from trading.strategy_runner.adapters import (
    AdapterRegistry,
    AdapterResult,
    LegacyStrategyResultAdapter,
    MultifactorAdmissionAdapter,
    StrategyAdapter,
    StrategyPackageAdapter,
    adapt_strategy_payload,
    zero_cr091_operation_counters,
)
from trading.strategy_runner.artifact_bundle import (
    RunArtifactBundle,
    inspect_run_artifact_bundle,
    replay_run_artifact_bundle,
    validate_run_artifact_bundle,
    write_run_artifact_bundle,
)
from trading.strategy_runner.cache import ActivePackagePointer, resolve_active_package
from trading.strategy_runner.evidence import EvidenceSummary, build_evidence_summary, write_evidence_summary
from trading.strategy_runner.evidence_index import RunEvidenceIndex, write_run_evidence_index
from trading.strategy_runner.live_switch_deferred import (
    LiveSwitchDecisionItem,
    LiveSwitchDeferredScenarioPack,
    build_deferred_live_switch_scenario_pack,
)
from trading.strategy_runner.package_exchange import (
    ExchangeOperationResult,
    PackageExchangeError,
    check_exchange,
    create_fake_exchange_root,
    fake_publish_package,
    fake_pull_package,
    validate_package,
)
from trading.strategy_runner.package_loader import StrategyPackage, load_strategy_package
from trading.strategy_runner.readonly_gateway import (
    FakeReadonlyQmtTransport,
    ReadonlyGatewayClient,
    ReadonlyGatewayResult,
    ReadonlyGatewayRuntimeConfig,
)
from trading.strategy_runner.run_registry import (
    RunRegistryEntry,
    append_run_registry_entry,
    append_run_registry_from_bundle,
    append_run_registry_from_result,
    inspect_run_registry_entry,
    read_run_registry,
)
from trading.strategy_runner.result import RunResult, write_run_result
from trading.strategy_runner.run_spec import RunSpec, RunSpecError
from trading.strategy_runner.runner import run_strategy_package, run_strategy_package_from_path, run_strategy_package_from_spec_file
from trading.strategy_runner.simulation_activation import (
    FunctionSimulationGateway,
    SimulationActivationRequest,
    SimulationActivationResult,
    SimulationExecutionAction,
    SimulationExecutionEngineRequest,
    SimulationExecutionEngineResult,
    SimulationGateway,
    SimulationOpenOrderRef,
    activate_simulation_orders,
    blocked_simulation_gateway,
    execute_simulation_order_plan,
)
from trading.strategy_runner.simulation_admission import (
    RunnerAdmissionContractResult,
    operator_signal_rows_from_admission,
    validate_strategy_admission_for_runner,
)
from trading.strategy_runner.simulation_evidence import (
    SimulationEvidenceValidationResult,
    allowed_evidence_data_classes,
    build_operator_evidence_index,
    validate_operator_evidence,
)
from trading.strategy_runner.simulation_operations import (
    SimulationOperationalItem,
    SimulationStabilityWindowDefinition,
    build_default_stability_window_definition,
    build_exception_recovery_matrix,
    build_pre_trading_window_checklist,
)
from trading.strategy_runner.simulation_reconciliation import (
    SimulationReconciliationRequest,
    SimulationReconciliationResult,
    reconcile_simulation_run,
)
from trading.strategy_runner.simulation_runbook import (
    SimulationOperationalRunbook,
    SimulationRunbookStep,
    build_simulation_operational_runbook,
)
from trading.strategy_runner.simulation_order_plan import (
    SimulationOrderPlanItem,
    SimulationOrderPlanRequest,
    SimulationOrderPlanResult,
    build_simulation_order_plan,
)
from trading.strategy_runner.simulation_operator import (
    EvidencePersistencePolicy,
    MultifactorSimulationOperatorRequest,
    MultifactorSimulationOperatorResult,
    RuntimeQmtSimulationGateway,
    StabilityWindowPolicy,
    build_runtime_qmt_client,
    request_from_mapping,
    run_multifactor_simulation_fixture_operator,
    run_multifactor_simulation_operator,
    write_operator_evidence,
)
from trading.strategy_runner.target_portfolio import (
    MultifactorSignalRow,
    MultifactorTargetPortfolioResult,
    TargetPortfolioSnapshot,
    build_multifactor_target_portfolio,
)

__all__ = (
    "ActivePackagePointer",
    "AdapterRegistry",
    "AdapterResult",
    "EvidenceSummary",
    "ExchangeOperationResult",
    "FakeReadonlyQmtTransport",
    "LegacyStrategyResultAdapter",
    "LiveSwitchDecisionItem",
    "LiveSwitchDeferredScenarioPack",
    "MultifactorAdmissionAdapter",
    "ReadonlyGatewayClient",
    "ReadonlyGatewayResult",
    "ReadonlyGatewayRuntimeConfig",
    "RunResult",
    "RunEvidenceIndex",
    "RunArtifactBundle",
    "RunRegistryEntry",
    "RunnerAdmissionContractResult",
    "RunSpec",
    "RunSpecError",
    "SimulationActivationRequest",
    "SimulationActivationResult",
    "SimulationEvidenceValidationResult",
    "SimulationExecutionAction",
    "SimulationExecutionEngineRequest",
    "SimulationExecutionEngineResult",
    "SimulationGateway",
    "SimulationOperationalRunbook",
    "SimulationOperationalItem",
    "SimulationOpenOrderRef",
    "SimulationOrderPlanItem",
    "SimulationOrderPlanRequest",
    "SimulationOrderPlanResult",
    "SimulationReconciliationRequest",
    "SimulationReconciliationResult",
    "SimulationRunbookStep",
    "SimulationStabilityWindowDefinition",
    "PackageExchangeError",
    "StrategyAdapter",
    "StrategyPackage",
    "StrategyPackageAdapter",
    "MultifactorSignalRow",
    "EvidencePersistencePolicy",
    "MultifactorSimulationOperatorRequest",
    "MultifactorSimulationOperatorResult",
    "RuntimeQmtSimulationGateway",
    "StabilityWindowPolicy",
    "MultifactorTargetPortfolioResult",
    "TargetPortfolioSnapshot",
    "adapt_strategy_payload",
    "build_multifactor_target_portfolio",
    "build_operator_evidence_index",
    "build_runtime_qmt_client",
    "build_default_stability_window_definition",
    "build_deferred_live_switch_scenario_pack",
    "build_exception_recovery_matrix",
    "build_pre_trading_window_checklist",
    "build_simulation_operational_runbook",
    "build_simulation_order_plan",
    "build_evidence_summary",
    "check_exchange",
    "create_fake_exchange_root",
    "fake_publish_package",
    "fake_pull_package",
    "load_strategy_package",
    "resolve_active_package",
    "run_strategy_package",
    "run_strategy_package_from_path",
    "run_strategy_package_from_spec_file",
    "FunctionSimulationGateway",
    "activate_simulation_orders",
    "execute_simulation_order_plan",
    "reconcile_simulation_run",
    "append_run_registry_entry",
    "append_run_registry_from_bundle",
    "append_run_registry_from_result",
    "inspect_run_artifact_bundle",
    "inspect_run_registry_entry",
    "read_run_registry",
    "request_from_mapping",
    "replay_run_artifact_bundle",
    "run_multifactor_simulation_operator",
    "run_multifactor_simulation_fixture_operator",
    "validate_run_artifact_bundle",
    "validate_package",
    "validate_operator_evidence",
    "validate_strategy_admission_for_runner",
    "allowed_evidence_data_classes",
    "operator_signal_rows_from_admission",
    "write_evidence_summary",
    "write_operator_evidence",
    "write_run_artifact_bundle",
    "write_run_evidence_index",
    "write_run_result",
    "blocked_simulation_gateway",
    "zero_cr091_operation_counters",
)
